
FIND_PATH(ROCKSDB_INCLUDE_DIR NAMES rocksdb/db.h PATHS "$ENV{ROCKSDB_DIR}/include")
if (DYNAMIC_LIB)
  FIND_LIBRARY(ROCKSDB_LIBRARIES NAMES rocksdb PATHS "$ENV{ROCKSDB_DIR}/lib")
else()
  FIND_LIBRARY(ROCKSDB_LIBRARIES NAMES librocksdb.a rocksdb PATHS "$ENV{ROCKSDB_DIR}/lib")
endif()

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ROCKSDB DEFAULT_MSG ROCKSDB_INCLUDE_DIR ROCKSDB_LIBRARIES)

IF(ROCKSDB_FOUND)
    MESSAGE(STATUS "Found Rocksdb at ${ROCKSDB_INCLUDE_DIR}")
    MARK_AS_ADVANCED(ROCKSDB_INCLUDE_DIR ROCKSDB_LIBRARIES)
ELSE()
    MESSAGE(FATAL_ERROR "ROCKSDB NOT FOUND")
ENDIF()
