
FIND_PATH(CZMQ_INCLUDE_DIR NAMES czmq.h PATHS "$ENV{CZMQ_DIR}/include")
FIND_LIBRARY(CZMQ_LIBRARIES NAMES czmq)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CZMQ DEFAULT_MSG CZMQ_INCLUDE_DIR CZMQ_LIBRARIES)

IF(CZMQ_FOUND)
    #    MESSAGE(STATUS "Found czmq at ${CZMQ_INCLUDE_DIR}")
    MARK_AS_ADVANCED(CZMQ_INCLUDE_DIR CZMQ_LIBRARIES)
ENDIF()
