
FIND_PATH(GLOG_INCLUDE_DIR NAMES glog/logging.h PATHS "$ENV{GLOG_DIR}/include")
if (GEN_DYNAMIC)
  FIND_LIBRARY(GLOG_LIBRARIES NAMES glog)
else()
  FIND_LIBRARY(GLOG_LIBRARIES NAMES libglog.a glog)
endif()

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLOG DEFAULT_MSG GLOG_INCLUDE_DIR GLOG_LIBRARIES)

IF(GLOG_FOUND)
    #    MESSAGE(STATUS "Found glog at ${GLOG_INCLUDE_DIR}")
    MARK_AS_ADVANCED(GLOG_INCLUDE_DIR GLOG_LIBRARIES)
ELSE()
    MESSAGE(FATAL_ERROR "Glog NOT FOUND")
ENDIF(GLOG_FOUND)
