SET(USTORE_INCLUDE_DIRS "")
SET(USTORE_LINKER_LIBS "")
SET(USTORE_DEFINITIONS "")

# --- [ LevelDB
IF (USE_LEVELDB)
  MESSAGE(STATUS "Use LevelDB as chunk storage")
  FIND_PACKAGE(LevelDB REQUIRED)
  LIST(APPEND USTORE_INCLUDE_DIRS PUBLIC ${LevelDB_INCLUDES})
  LIST(APPEND USTORE_LINKER_LIBS PUBLIC ${LevelDB_LIBRARIES})
  add_definitions(-DUSE_LEVELDB)
ENDIF()

# --- [ Snappy
IF (USE_LEVELDB)
  FIND_PACKAGE(Snappy REQUIRED)
  LIST(APPEND USTORE_INCLUDE_DIRS PRIVATE ${Snappy_INCLUDE_DIR})
  LIST(APPEND USTORE_LINKER_LIBS PRIVATE ${Snappy_LIBRARIES})
ENDIF()
