SET(USTORE_INCLUDE_DIRS "")
SET(USTORE_LINKER_LIBS "")
SET(USTORE_DEFINITIONS "")

FIND_PACKAGE(Protobuf REQUIRED)

# --- [ LevelDB
IF (USE_LEVELDB)
  MESSAGE(STATUS "Use LevelDB as chunk storage")
  FIND_PACKAGE(LevelDB REQUIRED)
  LIST(APPEND USTORE_INCLUDE_DIRS ${LevelDB_INCLUDES})
  LIST(APPEND USTORE_LINKER_LIBS ${LevelDB_LIBRARIES})
  ADD_DEFINITIONS(-DUSE_LEVELDB)
ENDIF()

# --- [ Snappy
IF (USE_LEVELDB)
  FIND_PACKAGE(Snappy REQUIRED)
  LIST(APPEND USTORE_INCLUDE_DIRS ${Snappy_INCLUDE_DIR})
  LIST(APPEND USTORE_LINKER_LIBS ${Snappy_LIBRARIES})
ENDIF()
